#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 11 21:03:56 2021

@author: janaki
"""

name = input('Enter name of student')
reg_num = input('Enter registration number of student ')
programme = input('Enter programme name')
print('Name: ',name)
print('Register number is ',reg_num)
print('Programme is',programme)