#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 11 21:06:28 2021

@author: janaki
"""

num1 = input('Enter first number')
num1 = int(num1)
num2 = int(input('Enter second number'))
added_val = num1+num2
print('Num1 is %d \n Num2 is %d \n value added is %d' %(num1,num2,added_val))